### ISSUE TITLE
board is not initialized

### ISSUE THREAD

**Issue by rishabhjoshi** [salman-bhai/battleship#3]
board variable is not initialised.
Ocean is empty.

**Comment by sbshah97** [comment]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager) to understand better.

**Comment by sbshah97** [comment]
I believe this can be closed now!
